#!/usr/bin/env python3
# -*- coding: UTF-8 -*-
# -----------------------------------------------------------------------------
#
from random import shuffle

QUICK_BROWN_FOXES = [
    'A jovial sphinx quickly jumped over the back fence.',
    'A mad boxer shot a quick, gloved jab to the jaw of his dizzy opponent.',
    'A quick movement of the enemy will jeopardize six guns.',
    'Big jack quickly moved the box of vexing quartz.',
    'Big jumpy frogs vexed the quick fox with quartz.',
    'Blazing fox jumps quickly over the wavy rocks.',
    'Blowzy night-frumps vex’d Jack Q.',
    'Fifty jolly wax figures have puzzled the quizzical judge.',
    'Flecks of quartz vex the jumping brown fox quickly.',
    'Flick my box with jolly, quick, vexing wizards.',
    'Foxy Jack quickly vexed the wizard with a bold jump.',
    'Foxy jacks quizzed the brave wizard on vexing jumps.',
    'Giant zephyrs blow quickly over the big waves.',
    'Grumpy wizards make toxic brew for the evil queen and jack.',
    'Grumpy wizards vex bold Jack quickly.',
    'Jack and the quick fox both jumped over the big box.',
    'Jack quickly moved the boxes of bright quartz.',
    'Jack quickly puzzled the vexed quiz master.',
    'Jack quietly bags a dozen big jumping foxes.',
    'Jack was quickly puzzled by the vexing fox and quiz.',
    'Jackdaws love my big sphinx of quartz.',
    'Jinxed wizards pluck ivy from the big quilt.',
    'Jovial zephyrs blow quickly, vexing the big fox.',
    'Jumping squirrels vex the big, quick, lazy dog.',
    'Jumpy kids quiz brave zombies with vexed fox.',
    'Jumpy squirrels vex bold wizards quickly.',
    'Jumpy zebras vex bold foxes in a quick frenzy.',
    'Mr Jock, TV quiz PhD, bags few lynx.',
    'Pack my box with five dozen liquor jugs.',
    'Quick vexed wizards jump over the box of jumping foxes.',
    'Quick wafting zephyrs vex bold Jim.',
    'Quick wizards vex bold jumping foxes in a frenzy.',
    'Six big jumping foxes vexed the quick wizard’s box.',
    'Sphinx of black quartz, judge my vow.',
    'The jay, pig, fox, zebra, and my dogs quack.',
    'The wizard’s box quickly vexes the jumping fox.',
    'The wizard’s vexing, quick box jumped over the lazy dog.',
    'The zebra jumped quickly across the frosty box.',
    'Vexed nymphs fly quickly over hot azaleas.',
    'Vexed squirrels jump quickly over brown logs.',
    'Vexing dwarves quickly jump for a big quiz.',
    'Vixens jump quickly, grasping the wizard’s box.',
    'Waltz, nymph, for quick jigs vex Bud.',
    'We swiftly jump over a dozen tricky obstacles.',
    'Zebras jump quickly on the vexing fox.',
    'Zoe quickly jumps over a big, vexing fox.',
    'Zoe won a jiffy bag with quick, vexing hops.',
]
shuffle(QUICK_BROWN_FOXES)